---
title: "Teste Markdown"
author: "Desirrê Petters-Vandresen"
date: "26/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pacotes necessários

```{r}
library(tidyverse)
library(colorspace)

```

## Cores necessárias

```{r}
colors <- sequential_hcl(3, palette = "viridis")

```

## Exemplo

Gráficos com comprimento das sépalas de diferentes espécies de *Iris* (*I. setosa*, *I. versicolor*, *I. virginica*), box-plot e violin-plot com e sem espalhamento de pontos (jitter)

### Box-plot

```{r}
iris_boxplot <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + geom_boxplot(notch = F) + ggtitle("Sépalas de Iris") + ylab("Comprimento da sépala") + xlab("Espécie") + scale_fill_manual(values = c(colors)) 

iris_boxplot_jitter <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + geom_boxplot(notch = F) + ggtitle("Sépalas de Iris") + ylab("Comprimento da sépala") + xlab("Espécie") + scale_fill_manual(values = c(colors)) + geom_jitter()

iris_boxplot

iris_boxplot_jitter

# Salvando as imagens

png("Iris (Boxplot).png")
iris_boxplot
dev.off()

png("Iris (Boxplot), jitter.png")
iris_boxplot_jitter
dev.off()

pdf("Iris (Boxplot).pdf")
iris_boxplot
dev.off()

pdf("Iris (Boxplot), jitter.pdf")
iris_boxplot_jitter
dev.off()

```

### Violin plot

```{r}
iris_violin <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + geom_violin() + ggtitle("Sépalas de Iris") + ylab("Comprimento da sépala") + xlab("Espécie") + scale_fill_manual(values = c(colors))

iris_violin_jitter <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + geom_violin() + ggtitle("Sépalas de Iris") + ylab("Comprimento da sépala") + xlab("Espécie") + scale_fill_manual(values = c(colors)) + geom_jitter()

iris_violin

iris_violin_jitter

# Salvando as imagens

png("Iris (Violin).png")
iris_violin
dev.off()

png("Iris (Violin), jitter.png")
iris_violin_jitter
dev.off()

pdf("Iris (Violin).pdf")
iris_violin
dev.off()

pdf("Iris (Violin), jitter.pdf")
iris_violin_jitter
dev.off()

```




